### ISSUE TITLE
cegmonc2az.asm assemble arithmetic problem

### ISSUE THREAD

**Issue by PhilByte** [sjgray/OSI-monitor-roms#1]
I am usiing this assembler listing with my home built 6502 system. In may ways it duplicates the Ohio superboard I had years ago.
Major difference is rearranging all IO to be in the $Dxxx segment and uing a PS2 keyboard instead of the original scanned matrix. (Interface is similar to ACIA)
To the problem( about 80 lines down):
The screen is still 1k at $D000-$D3FF but the assembler listing calculation does not give the correct result.
```
SWIDTH	=	COLS-1
TOP	=	SCREEN+START
BASE	=	ROWS-1*WIDTH+TOP
BOT	=	SIZE+1*1024+SCREEN
```
For my board: SCREEN = $D000, WIDTH = 32, SIZE =0, START =69, COLS = 24. ROWS = 26
The calculations give (verified by examining the output file):
SWIDTH = 23
TOP = $D045
BASE = $D03F
BOT = $D400

 The calculation for BASE gives $D035 which is clearly (now) not correct and gave some strange results.
The formula should have been (NB parentheses):
BASE = (ROWS-1) * WIDTH + TOP which gives $D365 and works correctly.
As it happens the formula for BOT was OK for my system (accidental) but it should be:
BOT	= (SIZE+1) * 1024 + SCREEN
Admittably I am not using the same assembler but I would assume that the normal arithmetic precedence rules would be followed. (Mine is VASM oldstyle)
I think this may also apply to other listings.
Hope that is useful
Phil

**Comment by sjgray** [comment]
Yes, I see. The files in the original source folder were disassembled by someone else and used as a starting point for my changes.
If you look at my new code "cegmon-sjg.asm" line 308 you'll see my changes:

LWIDTH	= COLS-1		; Logical line width -1
TOP	= SCREEN+START		; "HOME" position
BOT	= SCREEN+(SIZE+1)*1024	; End of physical screen RAM
BASE	= TOP+(ROWS-1)*WIDTH	; Start of Last Line of screen

For historical reasons I don't think I want to update anything in the original source folder.

**Comment by sjgray** [comment]
Original files will be left as-is. I suggest using my customized code.

**Comment by PhilByte** [comment]
Perhaps add a note to any appropriate readme files.
I'm now about to strip out any vestiges of the old keyboard handler and go for 32x28 VGA display.
Before that I've got to match PS2 scan codes to OSI key codes in the converter. 
Mostly correct ASCII codes but some keys give odd results.
(Couldn't get or make a usable keyboard to the original design at reasonable cost - TACT, perfboard and wires was awful)
I used your listings because the label format 'L<address>' made life easy when deleting or replacing sections.
I must change my disassembler to give that result as an option. (Currently 'A#', 'B#' or 'Z#' for abs, branch or ZP.
Thanks
Phil

**Comment by sjgray** [comment]
Done. I've updated the readme and also added additional monitor roms for future disassembling. You might want to check out my own disassembler, which I used to disassemble the WEMON binary. It's built into the viewer of my CBM-Transfer utility. I added a nice block commenting feature yesterday. It also has a code tracer which is handy for finding data tables.
